gnu:
  build: NO
  version: 9.3.0

openmpi:
  build: NO
  version: 4.0.1

cmake:
  build: NO
  version: 3.17.2

jpeg:
  build: NO
  version: 9.1.0

zlib:
  build: NO
  version: 1.2.11

png:
  build: NO
  version: 1.6.35

szip:
  build: NO
  version: 2.1.1

jasper:
  build: NO
  version: 2.0.15

udunits:
  build: NO
  version: 2.2.26

hdf5:
  build: NO
  version: 1.10.6

pnetcdf:
  build: NO
  version: 1.12.1

netcdf:
  build: NO
  version: 4.7.4

netcdf_f:
  build: NO
  version: 4.5.3

netcdf_cxx:
  build: NO
  version: 4.3.1

nccmp:
  build: NO
  version: 1.8.6.5

nco:
  build: NO
  version: 4.7.9

pio:
  build: NO
  version: 2.5.0

esmf:
  build: NO
  version: 8_0_0

gptl:
  build: NO
  version: 8.0.2

fftw:
  build: NO
  version: 3.3.8

tau2:
  build: NO
  version: 3.25.1

bacio:
  build: NO
  version: v2.4.0
  install_as: 2.4.0

sigio:
  build: NO
  version: v2.3.0
  install_as: 2.3.0

sfcio:
  build: NO
  version: v1.4.0
  install_as: 1.4.0

gfsio:
  build: NO
  version: v1.4.0
  install_as: 1.4.0

w3nco:
  build: NO
  version: v2.4.0
  install_as: 2.4.0

sp:
  build: NO
  version: v2.3.0
  install_as: 2.3.0

ip:
  build: NO
  version: v3.3.0
  install_as: 3.3.0

ip2:
  build: NO
  version: v1.1.0
  install_as: 1.1.0

landsfcutil:
  build: NO
  version: v2.4.0
  install_as: 2.4.0

nemsio:
  build: NO
  version: v2.5.1
  install_as: 2.5.1

nemsiogfs:
  build: NO
  version: v2.5.0
  install_as: 2.5.0

w3emc:
  build: NO
  version: v2.7.0
  install_as: 2.7.0

g2:
  build: NO
  version: v3.4.0
  install_as: 3.4.0

g2tmpl:
  build: NO
  version: v1.9.0
  install_as: 1.9.0

crtm:
  build: NO
  version: v2.3.0
  install_as: 2.3.0

nceppost:
  build: NO
  version: dceca26
  install_as: dceca26

wrf_io:
  build: NO
  version: v1.1.1-cmake
  install_as: 1.1.1

bufr:
  build: NO
  version: bufr_v11.3.1.1
  install_as: 11.3.1.1

wgrib2:
  build: NO
  version: v2.0.8-cmake-v1.0.2
  install_as: 2.0.8
