gnu:
  build: NO
  version: 9.3.0

mpi:
  build: NO
  flavor: openmpi
  version: 4.0.1

cmake:
  build: NO
  version: 3.17.2

jpeg:
  build: YES
  version: 9.1.0

zlib:
  build: YES
  version: 1.2.11

png:
  build: YES
  version: 1.6.35

szip:
  build: YES
  version: 2.1.1

jasper:
  build: YES
  version: 2.0.15

udunits:
  build: YES
  version: 2.2.26

hdf5:
  build: NO
  version: 1.10.6
  shared: YES
  enable_szip: NO
  enable_zlib: YES

pnetcdf:
  build: NO
  version: 1.12.1
  shared: YES

netcdf:
  build: NO
  shared: YES
  enable_pnetcdf: NO
  version_c: 4.7.4
  version_f: 4.5.3
  version_cxx: 4.3.1

nccmp:
  build: NO
  version: 1.8.7.0

nco:
  build: NO
  version: 4.9.3

pio:
  build: NO
  version: 2.5.1
  enable_pnetcdf: NO
  enable_gptl: NO

esmf:
  build: NO
  version: 8_1_0_beta_snapshot_27
  shared: YES
  enable_pnetcdf: NO
  debug: NO

bacio:
  build: NO
  version: v2.4.1
  install_as: 2.4.1

sigio:
  build: NO
  version: v2.3.2
  install_as: 2.3.2

sfcio:
  build: NO
  version: v1.4.1
  install_as: 1.4.1

gfsio:
  build: NO
  version: v1.4.1
  install_as: 1.4.1

w3nco:
  build: NO
  version: v2.4.1
  install_as: 2.4.1

sp:
  build: NO
  version: v2.3.3
  install_as: 2.3.3
  openmp: ON

ip:
  build: NO
  version: v3.3.3
  install_as: 3.3.3
  openmp: ON

ip2:
  build: NO
  version: v1.1.2
  install_as: 1.1.2
  openmp: ON

landsfcutil:
  build: NO
  version: v2.4.1
  install_as: 2.4.1

nemsio:
  build: NO
  version: v2.5.2
  install_as: 2.5.2

nemsiogfs:
  build: NO
  version: v2.5.3
  install_as: 2.5.3

w3emc:
  build: NO
  version: v2.7.3
  install_as: 2.7.3

g2:
  build: NO
  version: v3.4.1
  install_as: 3.4.1

g2tmpl:
  build: NO
  version: v1.9.1
  install_as: 1.9.1

crtm:
  build: NO
  version: v2.3.0
  install_as: 2.3.0

nceppost:
  build: NO
  version: dceca26
  install_as: dceca26
  openmp: ON

wrf_io:
  build: NO
  version: v1.1.1-cmake-v5
  install_as: 1.1.1
  openmp: ON

bufr:
  build: NO
  version: bufr_v11.4.0
  install_as: 11.4.0

wgrib2:
  build: NO
  version: v2.0.8-cmake-v5
  install_as: 2.0.8
  openmp: OFF
  spectral: OFF
  ipolates: 0

prod_util:
  build: NO
  version: v1.2.1
  install_as: 1.2.1

grib_util:
  build: NO
  version: v1.2.1
  install_as: 1.2.1
  openmp: ON

boost:
  build: YES
  version: 1.68.0
  level: headers-only

eigen:
  build: YES
  version: 3.3.7

gsl_lite:
  build: YES
  version: 0.37.0

gptl:
  build: NO
  version: 8.0.2

fftw:
  build: NO
  version: 3.3.8

tau2:
  build: NO
  version: 3.25.1

cgal:
  build: NO
  version: 5.0.2

ecbuild:
  build: YES
  version: release-stable
  repo: jcsda

eckit:
  build: YES
  version: release-stable
  repo: jcsda

fckit:
  build: YES
  version: release-stable
  repo: jcsda

atlas:
  build: YES
  version: release-stable
  repo: jcsda
