gnu:
  build: NO
  version: 9.3.0

mpi:
  build: NO
  flavor: openmpi
  version: 4.0.1

cmake:
  build: NO
  version: 3.17.2

jpeg:
  build: NO
  version: 9.1.0

zlib:
  build: NO
  version: 1.2.11

png:
  build: NO
  version: 1.6.35

szip:
  build: NO
  version: 2.1.1

jasper:
  build: NO
  version: 2.0.15

udunits:
  build: NO
  version: 2.2.26

hdf5:
  build: NO
  version: 1.10.6
  shared: YES
  enable_szip: NO
  enable_zlib: NO

pnetcdf:
  build: NO
  version: 1.12.1
  shared: YES

netcdf:
  build: NO
  shared: YES
  enable_pnetcdf: NO
  version_c: 4.7.4
  version_f: 4.5.3
  version_cxx: 4.3.1

nccmp:
  build: NO
  version: 1.8.7.0

nco:
  build: NO
  version: 4.9.3

pio:
  build: NO
  version: 2.5.1
  enable_pnetcdf: NO

esmf:
  build: NO
  version: 8_1_0_beta_snapshot_00
  shared: YES
  enable_pnetcdf: NO

gptl:
  build: NO
  version: 8.0.2

fftw:
  build: NO
  version: 3.3.8

tau2:
  build: NO
  version: 3.25.1

bacio:
  build: NO
  version: v2.4.0
  install_as: 2.4.0
  openmp: OFF

sigio:
  build: NO
  version: v2.3.0
  install_as: 2.3.0
  openmp: OFF

sfcio:
  build: NO
  version: v1.4.0
  install_as: 1.4.0
  openmp: OFF

gfsio:
  build: NO
  version: v1.4.0
  install_as: 1.4.0
  openmp: OFF

w3nco:
  build: NO
  version: v2.4.0
  install_as: 2.4.0
  openmp: OFF

sp:
  build: NO
  version: v2.3.0
  install_as: 2.3.0
  openmp: OFF

ip:
  build: NO
  version: v3.3.0
  install_as: 3.3.0
  openmp: OFF

ip2:
  build: NO
  version: v1.1.0
  install_as: 1.1.0
  openmp: OFF

landsfcutil:
  build: NO
  version: v2.4.0
  install_as: 2.4.0
  openmp: OFF

nemsio:
  build: NO
  version: v2.5.1
  install_as: 2.5.1
  openmp: OFF

nemsiogfs:
  build: NO
  version: v2.5.0
  install_as: 2.5.0
  openmp: OFF

w3emc:
  build: NO
  version: v2.7.0
  install_as: 2.7.0
  openmp: OFF

g2:
  build: NO
  version: v3.4.0
  install_as: 3.4.0
  openmp: OFF

g2tmpl:
  build: NO
  version: v1.9.0
  install_as: 1.9.0
  openmp: OFF

crtm:
  build: NO
  version: v2.3.0
  install_as: 2.3.0
  openmp: OFF

nceppost:
  build: NO
  version: dceca26
  install_as: dceca26
  openmp: OFF

wrf_io:
  build: NO
  version: v1.1.1-cmake
  install_as: 1.1.1
  openmp: OFF

bufr:
  build: NO
  version: bufr_v11.3.1.1
  install_as: 11.3.1.1
  openmp: OFF

wgrib2:
  build: NO
  version: v2.0.8-cmake-v1.0.2
  install_as: 2.0.8
  openmp: OFF
