gnu:
  build: NO
  version: 9.3.0

mpi:
  build: NO
  flavor: openmpi
  version: 4.0.1

cmake:
  build: NO
  bootstrap: YES
  version: 3.20.1

jpeg:
  build: YES
  version: 9.1.0

zlib:
  build: YES
  version: 1.2.11

png:
  build: YES
  version: 1.6.35

szip:
  build: YES
  version: 2.1.1

jasper:
  build: YES
  version: 2.0.25

udunits:
  build: YES
  version: 2.2.28

hdf5:
  build: YES
  version: 1.10.6
  shared: YES
  enable_szip: NO
  enable_zlib: YES

pnetcdf:
  build: NO
  version: 1.12.1
  shared: YES

netcdf:
  build: YES
  shared: YES
  enable_pnetcdf: NO
  version_c: 4.7.4
  version_f: 4.5.3
  version_cxx: 4.3.1
  disable_cxx: YES

nccmp:
  build: YES
  version: 1.8.9.0

nco:
  build: NO
  version: 4.9.3

cdo:
  build: YES
  version: 1.9.8

pio:
  build: YES
  version: 2.5.3
  enable_pnetcdf: NO
  enable_gptl: NO

esmf:
  build: YES
  version: 8_1_1
  shared: YES
  enable_pnetcdf: NO
  debug: NO

fms:
  build: YES
  version: 2020.04.03
  repo: noaa-gfdl
  cmake_opts: "-DGFS_PHYS=ON -D64BIT=ON -DOPENMP=ON"

bacio:
  build: YES
  version: v2.4.1
  install_as: 2.4.1

sigio:
  build: YES
  version: v2.3.2
  install_as: 2.3.2

sfcio:
  build: YES
  version: v1.4.1
  install_as: 1.4.1

gfsio:
  build: YES
  version: v1.4.1
  install_as: 1.4.1

w3nco:
  build: YES
  version: v2.4.1
  install_as: 2.4.1

sp:
  build: YES
  version: v2.3.3
  install_as: 2.3.3
  openmp: ON

ip:
  build: YES
  version: v3.3.3
  install_as: 3.3.3
  openmp: ON

ip2:
  build: YES
  version: v1.1.2
  install_as: 1.1.2
  openmp: ON

landsfcutil:
  build: YES
  version: v2.4.1
  install_as: 2.4.1

nemsio:
  build: YES
  version: v2.5.2
  install_as: 2.5.2

nemsiogfs:
  build: YES
  version: v2.5.3
  install_as: 2.5.3

w3emc:
  build: YES
  version: v2.7.3
  install_as: 2.7.3

g2:
  build: YES
  version: v3.4.1
  install_as: 3.4.1

g2c:
  build: YES
  version: v1.6.2
  install_as: 1.6.2

g2tmpl:
  build: YES
  version: v1.9.1
  install_as: 1.9.1

crtm:
  build: YES
  version: v2.3.0
  install_as: 2.3.0

upp:
  build: YES
  version: upp_v10.0.5
  install_as: 10.0.5
  openmp: ON

wrf_io:
  build: YES
  version: v1.1.1-cmake-v5
  install_as: 1.1.1
  openmp: ON

bufr:
  build: YES
  version: bufr_v11.5.0
  install_as: 11.5.0
  python: YES

wgrib2:
  build: YES
  version: v2.0.8-cmake-v6
  install_as: 2.0.8
  openmp: ON
  spectral: ON
  ipolates: 3

prod_util:
  build: YES
  version: v1.2.2
  install_as: 1.2.2

grib_util:
  build: YES
  version: v1.2.2
  install_as: 1.2.2
  openmp: ON

ncio:
  build: YES
  version: develop
  install_as: 1.0.0

boost:
  build: YES
  version: 1.68.0
  level: headers-only

eigen:
  build: YES
  version: 3.3.7

gsl_lite:
  build: YES
  version: 0.37.0

gptl:
  build: NO
  version: 8.0.2

fftw:
  build: NO
  version: 3.3.8

tau2:
  build: NO
  version: 3.25.1

cgal:
  build: NO
  version: 5.0.2

json:
  build: YES
  version: 3.9.1

json_schema_validator:
  build: YES
  version: 2.1.0

pybind11:
  build: YES
  version: 2.5.0

ecbuild:
  build: YES
  version: 3.6.1
  repo: ecmwf

eckit:
  build: YES
  version: 1.16.0
  repo: ecmwf

fckit:
  build: YES
  version: 0.9.2
  repo: ecmwf

atlas:
  build: YES
  version: 0.24.1
  repo: ecmwf

madis:
  build: YES
  version: 4.3
